import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import homeImage from "../public/homeImg.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CodeBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>&lt;CodeBlogs/&gt;</h1>
        <div className={styles.homeImage__container}>
          <Image
            className={styles.home__image}
            width={180}
            height={157}
            src={homeImage}
            alt="Home Image"
          />
        </div>

        <div className="blogs">
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  );
}
